# Generated by Django 4.1 on 2022-08-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1992-08-24'),
            preserve_default=False,
        ),
    ]
